version: '3.2'

services:
    db:
        build:
            context: .
            dockerfile: ./compose/production/postgres/Dockerfile
        volumes:
            - ./compose/data:/var/lib/postgresql/data
            - ./compose/backup:/backups
        env_file: 
            - compose.env
        ports:
            - "5433:5432"
    django:
        build:
            context: .
            dockerfile: ./compose/production/django/Dockerfile
        depends_on:
            - db
        env_file: 
            - compose.env
        volumes:
            - ./api:/app
        command: sh /gunicorn.sh
    nginx:
        image: nginx:1.13-alpine
        depends_on:
            - django
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
      
    
