version: '3.2'

services:
    db:
        image: mysql:8.0.2
        env_file: 
            - compose.env
        volumes:
            - ./compose/data/db:/var/lib/mysql
        ports:
            - "3307:3306"
    django:
        build:
            context: .
            dockerfile: ./compose/production/django/Dockerfile
        depends_on:
            - db
        env_file: 
            - compose.env
        volumes:
            - ./api:/app
        command: sh /gunicorn.sh
    nginx:
        image: nginx:1.13-alpine
        depends_on:
            - django
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
      
    
