version: '3.2'

services:
    db:
        image: mysql:8.0.2
        env_file: 
            - compose.env
        volumes:
            - ./compose/data/db:/var/lib/mysql
        ports:
            - "3306:3306"
    selenium:
        image: selenium/standalone-firefox:3.5.3-astatine
    django:
        build:
            context: .
            dockerfile: ./compose/production/django/Dockerfile
        depends_on:
            - db
        env_file: 
            - compose.env
        volumes:
            - ./api:/app
        command: sh /gunicorn.sh
    worker:
        build:
            context: .
            dockerfile: ./compose/production/django/Dockerfile
        depends_on:
         - db
         - selenium
        env_file: 
            - compose.env
        volumes:
            - ./api:/app
        command: sh /celeryworker.sh
    web:
        image: nginx:1.13-alpine
        depends_on:
            - django
        env_file: 
            - compose.env
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
    
